In [2]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

### Integracion en hipercubo con centro en c: (1, 0, 0, 0, 6.284, 0) y tamano delta: (0.5, 0.5, 0.5, 1.0547, 1.0547, 1.0547)

In [17]:
df = pd.read_csv("count_objects.csv")
df['ratio'] = df['numerical_count']/df['theoretical_count']
df

,transformation_type,numerical_count,theoretical_count,objects_generated,iteration,Unnamed: 5,Unnamed: 6,ratio
0,uniform_complete,5,4.938991,100000,1.0,NaN,NaN,1.012352
1,uniform_complete,6,4.938991,100000,2.0,NaN,NaN,1.214823
2,uniform_complete,6,4.938991,100000,3.0,NaN,NaN,1.214823
3,uniform_complete,6,4.938991,100000,4.0,NaN,NaN,1.214823
4,uniform_complete,6,4.938991,100000,5.0,NaN,NaN,1.214823
...,...,...,...,...,...,...,...,...
155,uniform_aewM,119535,117758.252156,100000000,16.0,NaN,NaN,1.015088
156,uniform_aewM,118178,117758.252156,100000000,17.0,NaN,NaN,1.003564
157,uniform_aewM,118323,117758.252156,100000000,18.0,NaN,NaN,1.004796
158,uniform_aewM,118647,117758.252156,100000000,19.0,NaN,NaN,1.007547
159,uniform_aewM,119147,117758.252156,100000000,20.0,NaN,NaN,1.011793

In [18]:
df_uniform = df[df['transformation_type'] == 'uniform_aewM']

# Gráfico base
fig = px.line(
    df_uniform, 
    x=' iteration', 
    y='ratio', 
    color='objects_generated', 
    markers=True
)

# Obtener los colores del gráfico
color_map = {}
for trace in fig.data:
    # A veces trace.name no es exactamente igual al valor de la columna, por eso lo forzamos a string
    color_map[str(trace.name)] = trace.line.color

# Agregar línea horizontal del promedio para cada categoría
for category in df_uniform['objects_generated'].unique():
    color = color_map.get(str(category), 'gray')  # color por defecto si no se encuentra
    avg_value = df_uniform.loc[df_uniform['objects_generated'] == category, 'ratio'].mean()

    fig.add_hline(
        y=avg_value,
        line=dict(color=color, width=2, dash='dot'),
        opacity=0.5
    )

# Ajustes visuales
fig.update_layout(
    title=dict(text="Numeric Experiment P_xyvxvy Uniform dxyz = 0.5", font=dict(size=20)),
    yaxis_title="Ratio",
    xaxis_title="Iteration",
    showlegend=True
)

fig.show()

In [19]:
df_complete = df[df['transformation_type'] == 'uniform_complete']

# Gráfico base
fig = px.line(
    df_complete, 
    x=' iteration', 
    y='ratio', 
    color='objects_generated', 
    markers=True
)

# Obtener los colores del gráfico
color_map = {}
for trace in fig.data:
    # A veces trace.name no es exactamente igual al valor de la columna, por eso lo forzamos a string
    color_map[str(trace.name)] = trace.line.color

# Agregar línea horizontal del promedio para cada categoría
for category in df_complete['objects_generated'].unique():
    color = color_map.get(str(category), 'gray')  # color por defecto si no se encuentra
    avg_value = df_complete.loc[df_complete['objects_generated'] == category, 'ratio'].mean()

    fig.add_hline(
        y=avg_value,
        line=dict(color=color, width=2, dash='dot'),
        opacity=0.5
    )

# Ajustes visuales
fig.update_layout(
    title=dict(text="Numeric Experiment P_X Uniform dxyz = 0.5", font=dict(size=20)),
    yaxis_title="Ratio",
    xaxis_title="Iteration",
    showlegend=True
)

fig.show()

### Integracion en hipercubo con centro en c: (1, 0, 0, 0, 6.284, 0) y tamano delta: (0.2, 0.2, 0.2, 1.0547, 1.0547, 1.0547)

In [3]:
df2 = pd.read_csv("count_objects2.csv")
df2

,transformation_type,numerical_count,theoretical_count,objects_generated,iteration,iteration
0,uniform_aewM,100,117.758252,100000,1.0,NaN
1,uniform_aewM,124,117.758252,100000,2.0,NaN
2,uniform_aewM,125,117.758252,100000,3.0,NaN
3,uniform_aewM,123,117.758252,100000,4.0,NaN
4,uniform_aewM,113,117.758252,100000,5.0,NaN
...,...,...,...,...,...,...
255,CMND_complete,1779,1894.233831,10000000,NaN,15.0
256,CMND_complete,1746,1894.233831,10000000,NaN,16.0
257,CMND_complete,1853,1894.233831,10000000,NaN,17.0
258,CMND_complete,1738,1894.233831,10000000,NaN,18.0
259,CMND_complete,1702,1894.233831,10000000,NaN,19.0

In [21]:
df_complete2 = df2[df2['transformation_type'] == 'uniform_complete']
df_complete2['ratio'] = df_complete2['numerical_count']/df_complete2['theoretical_count']
df_complete2

C:\Users\aguju\AppData\Local\Temp\ipykernel_12680\84550993.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,transformation_type,numerical_count,theoretical_count,objects_generated,iteration,iteration,ratio
80,uniform_complete,3,1.052543,100000,NaN,0.0,2.850240
81,uniform_complete,0,1.052543,100000,NaN,1.0,0.000000
82,uniform_complete,1,1.052543,100000,NaN,2.0,0.950080
83,uniform_complete,2,1.052543,100000,NaN,3.0,1.900160
84,uniform_complete,3,1.052543,100000,NaN,4.0,2.850240
...,...,...,...,...,...,...,...
155,uniform_complete,1054,1052.542834,100000000,NaN,15.0,1.001384
156,uniform_complete,1102,1052.542834,100000000,NaN,16.0,1.046988
157,uniform_complete,1195,1052.542834,100000000,NaN,17.0,1.135346
158,uniform_complete,1121,1052.542834,100000000,NaN,18.0,1.065040
159,uniform_complete,1118,1052.542834,100000000,NaN,19.0,1.062190

In [22]:
# Gráfico base
fig = px.line(
    df_complete2, 
    x='iteration', 
    y='ratio', 
    color='objects_generated', 
    markers=True
)

# Obtener los colores del gráfico
color_map = {}
for trace in fig.data:
    # A veces trace.name no es exactamente igual al valor de la columna, por eso lo forzamos a string
    color_map[str(trace.name)] = trace.line.color

# Agregar línea horizontal del promedio para cada categoría
for category in df_complete2['objects_generated'].unique():
    color = color_map.get(str(category), 'gray')  # color por defecto si no se encuentra
    avg_value = df_complete2.loc[df_complete2['objects_generated'] == category, 'ratio'].mean()

    fig.add_hline(
        y=avg_value,
        line=dict(color=color, width=2, dash='dot'),
        opacity=0.5
    )

# Ajustes visuales
fig.update_layout(
    title=dict(text="Numeric Experiment P_X Uniform dxyz = 0.2", font=dict(size=20)),
    yaxis_title="Ratio",
    xaxis_title="Iteration",
    showlegend=True
)

fig.show()

In [24]:
df_complete3 = df2[df2['transformation_type'] == 'uniform_complete_sini']
df_complete3['ratio'] = df_complete3['numerical_count']/df_complete3['theoretical_count']

fig = px.line(
    df_complete3, 
    x='iteration', 
    y='ratio', 
    color='objects_generated', 
    markers=True
)

# Obtener los colores del gráfico
color_map = {}
for trace in fig.data:
    # A veces trace.name no es exactamente igual al valor de la columna, por eso lo forzamos a string
    color_map[str(trace.name)] = trace.line.color

# Agregar línea horizontal del promedio para cada categoría
for category in df_complete3['objects_generated'].unique():
    color = color_map.get(str(category), 'gray')  # color por defecto si no se encuentra
    avg_value = df_complete3.loc[df_complete3['objects_generated'] == category, 'ratio'].mean()

    fig.add_hline(
        y=avg_value,
        line=dict(color=color, width=2, dash='dot'),
        opacity=0.5
    )

# Ajustes visuales
fig.update_layout(
    title=dict(text="Numeric Experiment P_X Uniform dxyz = 0.2 sin(i)", font=dict(size=20)),
    yaxis_title="Ratio",
    xaxis_title="Iteration",
    showlegend=True
)

fig.show()

C:\Users\aguju\AppData\Local\Temp\ipykernel_12680\159891737.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [6]:
df2[df2["transformation_type"] == "CMND_complete"]

,transformation_type,numerical_count,theoretical_count,objects_generated,iteration,iteration
240,CMND_complete,1792,1894.233831,10000000,NaN,0.0
241,CMND_complete,1809,1894.233831,10000000,NaN,1.0
242,CMND_complete,1799,1894.233831,10000000,NaN,2.0
243,CMND_complete,1758,1894.233831,10000000,NaN,3.0
244,CMND_complete,1723,1894.233831,10000000,NaN,4.0
245,CMND_complete,1779,1894.233831,10000000,NaN,5.0
246,CMND_complete,1800,1894.233831,10000000,NaN,6.0
247,CMND_complete,1750,1894.233831,10000000,NaN,7.0
248,CMND_complete,1792,1894.233831,10000000,NaN,8.0
249,CMND_complete,1809,1894.233831,10000000,NaN,9.0
250,CMND_complete,1744,1894.233831,10000000,NaN,10.0
251,CMND_complete,1782,1894.233831,10000000,NaN,11.0
252,CMND_complete,1715,1894.233831,10000000,NaN,12.0
253,CMND_complete,1788,1894.233831,10000000,NaN,13.0
254,CMND_complete,1748,1894.233831,10000000,NaN,14.0
255,CMND_complete,1779,1894.233831,10000000,NaN,15.0
256,CMND_complete,1746,1894.233831,10000000,NaN,16.0
257,CMND_complete,1853,1894.233831,10000000,NaN,17.0
258,CMND_complete,1738,1894.233831,10000000,NaN,18.0
259,CMND_complete,1702,1894.233831,10000000,NaN,19.0

In [39]:
df3 = pd.read_csv("count_objects3.csv")
df3

,transformation_type,numerical_count,theoretical_count,objects_generated,iteration,ratio,description,integration_params
0,CMND_complete,1792,1894.233831,10000000,0,1.057050,NaN,NaN
1,CMND_complete,1809,1894.233831,10000000,1,1.047117,NaN,NaN
2,CMND_complete,1799,1894.233831,10000000,2,1.052937,NaN,NaN
3,CMND_complete,1758,1894.233831,10000000,3,1.077494,NaN,NaN
4,CMND_complete,1723,1894.233831,10000000,4,1.099381,NaN,NaN
...,...,...,...,...,...,...,...,...
90,CMND_complete,73816,63501.702526,10000000,5,0.860270,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
91,CMND_complete,73777,63501.702526,10000000,6,0.860725,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
92,CMND_complete,73689,63501.702526,10000000,7,0.861753,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
93,CMND_complete,73652,63501.702526,10000000,8,0.862186,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
94,CMND_complete,73498,63501.702526,10000000,9,0.863992,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."

In [43]:
df_cmnd_hypercube = df3[(df3['transformation_type'] == "CMND_complete")]
df_cmnd_hypercube

,transformation_type,numerical_count,theoretical_count,objects_generated,iteration,ratio,description,integration_params
0,CMND_complete,1792,1894.233831,10000000,0,1.057050,NaN,NaN
1,CMND_complete,1809,1894.233831,10000000,1,1.047117,NaN,NaN
2,CMND_complete,1799,1894.233831,10000000,2,1.052937,NaN,NaN
3,CMND_complete,1758,1894.233831,10000000,3,1.077494,NaN,NaN
4,CMND_complete,1723,1894.233831,10000000,4,1.099381,NaN,NaN
...,...,...,...,...,...,...,...,...
90,CMND_complete,73816,63501.702526,10000000,5,0.860270,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
91,CMND_complete,73777,63501.702526,10000000,6,0.860725,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
92,CMND_complete,73689,63501.702526,10000000,7,0.861753,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
93,CMND_complete,73652,63501.702526,10000000,8,0.862186,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
94,CMND_complete,73498,63501.702526,10000000,9,0.863992,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."

In [41]:
df_cmnd_sphere = df3[(df3['description'] == "sphere_CMND_complete")]
df_cmnd_sphere

,transformation_type,numerical_count,theoretical_count,objects_generated,iteration,ratio,description,integration_params
75,CMND_complete,7432,6350.170253,1000000,0,0.864404,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
76,CMND_complete,7470,6350.170253,1000000,1,0.866019,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
77,CMND_complete,7300,6350.170253,1000000,2,0.857818,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
78,CMND_complete,7477,6350.170253,1000000,3,0.853736,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
79,CMND_complete,7469,6350.170253,1000000,4,0.862455,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
80,CMND_complete,7192,6350.170253,1000000,5,0.860270,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
81,CMND_complete,7390,6350.170253,1000000,6,0.860725,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
82,CMND_complete,7303,6350.170253,1000000,7,0.861753,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
83,CMND_complete,7465,6350.170253,1000000,8,0.862186,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
84,CMND_complete,7413,63501.702526,1000000,9,0.863992,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
85,CMND_complete,73463,63501.702526,10000000,0,0.864404,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
86,CMND_complete,73326,63501.702526,10000000,1,0.866019,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
87,CMND_complete,74027,63501.702526,10000000,2,0.857818,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
88,CMND_complete,74381,63501.702526,10000000,3,0.853736,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
89,CMND_complete,73629,63501.702526,10000000,4,0.862455,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
90,CMND_complete,73816,63501.702526,10000000,5,0.860270,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
91,CMND_complete,73777,63501.702526,10000000,6,0.860725,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
92,CMND_complete,73689,63501.702526,10000000,7,0.861753,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
93,CMND_complete,73652,63501.702526,10000000,8,0.862186,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."
94,CMND_complete,73498,63501.702526,10000000,9,0.863992,sphere_CMND_complete,"{'center_sphere': array([1., 0., 0.]), 'radio_..."

In [42]:
fig = px.line(
    df_cmnd_sphere, 
    x='iteration', 
    y='ratio', 
    color='objects_generated', 
    markers=True
)

# Obtener los colores del gráfico
color_map = {}
for trace in fig.data:
    # A veces trace.name no es exactamente igual al valor de la columna, por eso lo forzamos a string
    color_map[str(trace.name)] = trace.line.color

# Agregar línea horizontal del promedio para cada categoría
for category in df_cmnd_sphere['objects_generated'].unique():
    color = color_map.get(str(category), 'gray')  # color por defecto si no se encuentra
    avg_value = df_cmnd_sphere.loc[df_cmnd_sphere['objects_generated'] == category, 'ratio'].mean()

    fig.add_hline(
        y=avg_value,
        line=dict(color=color, width=2, dash='dot'),
        opacity=0.5
    )

# Ajustes visuales
fig.update_layout(
    title=dict(text="Numeric Experiment P_X Uniform dxyz = 0.2 sin(i)", font=dict(size=20)),
    yaxis_title="Ratio",
    xaxis_title="Iteration",
    showlegend=True
)

fig.show()